### ISSUE TITLE
Missing paths.json

### ISSUE THREAD

**Issue by srama2512** [taochenshh/exp4nav#2]
Hi, 

Thank you for providing detailed instructions. I'm stuck at one of the final steps. After preparing the data, creating .obj and .mtl files, I ran 
```
python env_remove_components.py
```
I ended up with the following error:
```
Traceback (most recent call last):
  File "env_remove_components.py", line 81, in <module>
    main()
  File "env_remove_components.py", line 71, in main
    prefix=configs['par_path'])
with open(filename) as file:
FileNotFoundError: [Errno 2] No such file or directory: 'exp4nav/src/configs/paths.json'
```
I'm unable to locate `paths.json` in the repository or in House3D files. Am I missing some part of the installation instructions?

**Comment by taochenshh** [comment]
Thanks for pointing it out. I just added it. 

commit a492f0b6c962ff3f871d168c81fcf9df7104ba03
