### ISSUE TITLE
house-no-doors.obj files missing

### ISSUE THREAD

**Issue by srama2512** [taochenshh/exp4nav#3]
Hi,

I ran through the entire setup. The `house-no-doors.obj` files seem to be missing. I have the `house-no-doors.json` files. I'm assuming that these are generated via the [SUNCG scripts](https://github.com/shurans/SUNCGtoolbox#convert-to-objmtl). Could you provide the script that generates all the valid obj files? Also, `bad_houses.json` contains 774 houses. Is that right? That seems to cover all of the available houses from EQA.

**Comment by taochenshh** [comment]
The script (`make_houses.py`) was already there. I also updated the instructions. Thanks.

**Comment by taochenshh** [comment]
I just checked the `bad_houses.json` file again. It contains less than 80 houses.

**Comment by srama2512** [comment]
Thank you for the update! I think the issue with `bad_houses.json` was because these houses had not been extracted.
