### ISSUE TITLE
what is "obs_uint8[0].shape" in "rollout()"?

### ISSUE THREAD

**Issue by ghost** [taochenshh/exp4nav#7]
Hello,

Thank you for releasing your work and the corresponding code.
I wanted to you ask you abt some of the technicalities in the data generating process i.e. https://github.com/taochenshh/exp4nav/blob/548f05e4c7d55faac5ff071a7f089a940d6233b2/src/algos/ppo_map.py#L257 Ever since the SUNCG dataset was taken down, I have not been able to run the training code as is :(( 

As I understand, one `rollout` results in one sequence of maps and rgb images to feed as input to the LSTM. Therefore, I was expecting the shape of `obs_uint8[0]` (which is the rgb image) to be `(self.config['output_width'], self.config['output_width'], 3)`.

However, in line 268, the `batch_size` argument of `init_hidden` is set to `obs_uint8[0].shape[0]`, which I assumed to be `self.config['output_width']`. https://github.com/taochenshh/exp4nav/blob/548f05e4c7d55faac5ff071a7f089a940d6233b2/src/algos/ppo_map.py#L268`

Furthermore, in line 273, each element of `obs_uint8` is preprocessed via `imagenet_rgb_preprocess`, but it turns out that `imagenet_rgb_preprocess` expects a `np.array` input that has 4 dimensions instead of 3
https://github.com/taochenshh/exp4nav/blob/548f05e4c7d55faac5ff071a7f089a940d6233b2/src/utils/common.py#L29

So I was wondering what is the actual shape of the rgb image in `obs_uint8 = env.reset()`? Thank you in advance :)

**Comment by taochenshh** [comment]
As in PPO, there are multiple processes in a rollout. So the first dimension of rollout data is the number of processes (parallel agents). Hope this solved your issues.
