### ISSUE TITLE
how the occupancy map is filled in "get_seen_area"

### ISSUE THREAD

**Issue by ghost** [taochenshh/exp4nav#8]
Hello,

I was wondering how exactly the occupancy map is filled in `get_seen_area`. What I don't understand is WHICH GRID CELLS are assigned as "free / unoccupied (with value 2)" in the following line: https://github.com/taochenshh/exp4nav/blob/548f05e4c7d55faac5ff071a7f089a940d6233b2/src/envs/house3dRGBD.py#L296-L297 where https://github.com/taochenshh/exp4nav/blob/548f05e4c7d55faac5ff071a7f089a940d6233b2/src/envs/house3dRGBD.py#L287 and https://github.com/taochenshh/exp4nav/blob/548f05e4c7d55faac5ff071a7f089a940d6233b2/src/envs/house3dRGBD.py#L292

1. What is in each column in `points`?
2. What is `grid_locs` and how is it computed? (what is `self.L_min`?) 
3. What does `HEIGHT_THRESHOLD` refer to? (along which direction is it a threshold for?)

Forgive me for asking so many questions about the specifics of your code but please understand as there aren't many comments explaining what this part of the code actually does.
Thank you in advance :)

**Comment by taochenshh** [comment]
We just did height thresholding. Imagine your robot sees a point cloud of the world. How do you tell if which part of the point cloud belongs to obstacles? A simple way is to just based on the height of the point cloud. If the points are higher than a low threshold (5cm for example) and lower than a high threshold (2m for example), then you can say those points are very likely to belong to the obstacles that might affect the robot movement.
